name: Client Lint and Format

on:
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: client

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: client/yarn.lock

      - name: Lint with ESLint
        run: yarn run lint:fix

      - name: Format with Prettier
        run: yarn run format:fix

      - name: Look for modified files
        id: changes
        run: |
          echo "modified=$(
            if git status --porcelain | grep -P -q '^.*M'; then
              echo "false";
            else
              echo "true";
            fi
          )" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.changes.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -u

      - name: Push changes to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push
